//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PA_BlogProject_2021.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class BlogProjeContext : DbContext
    {
        public BlogProjeContext()
            : base("name=BlogProjeContext")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Abouts> Abouts { get; set; }
        public virtual DbSet<BlogDetails> BlogDetails { get; set; }
        public virtual DbSet<Blogs> Blogs { get; set; }
        public virtual DbSet<Comments> Comments { get; set; }
        public virtual DbSet<Contacts> Contacts { get; set; }
        public virtual DbSet<Roles> Roles { get; set; }
        public virtual DbSet<Sliders> Sliders { get; set; }
        public virtual DbSet<Tags> Tags { get; set; }
        public virtual DbSet<TeamDescriptions> TeamDescriptions { get; set; }
        public virtual DbSet<Users> Users { get; set; }
        public virtual DbSet<Teams> Teams { get; set; }
        public virtual DbSet<Services> Services { get; set; }
        public virtual DbSet<Portfolios> Portfolios { get; set; }
    }
}
