//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PA_BlogProject_2021.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TeamDescriptions
    {
        public int TeamDescriptionId { get; set; }
        public string FirstTitle { get; set; }
        public string SubTitle { get; set; }
        public string Title { get; set; }
        public string Description { get; set; }
        public string ImageURL { get; set; }
        public bool IsActive { get; set; }
    }
}
